<?php
exit;


class Database_Drive_Postgre_Result extends Drive_Database_Drive_Postgre_Result{}
class Ex_Database_Drive_Postgre_Result extends Drive_Database_Drive_Postgre_Result{}

class Database_Drive_Postgre_Transaction extends Drive_Database_Drive_Postgre_Transaction{}
class Ex_Database_Drive_Postgre_Transaction extends Drive_Database_Drive_Postgre_Transaction{}

class Database_Drive_Postgre extends Drive_Database_Drive_Postgre{}
class Ex_Database_Drive_Postgre extends Drive_Database_Drive_Postgre{}