<?php
exit;


class Database_Driver_Mongo_Result extends Driver_Database_Driver_Mongo_Result{}
class Ex_Database_Driver_Mongo_Result extends Driver_Database_Driver_Mongo_Result{}

class Database_Driver_Mongo extends Driver_Database_Driver_Mongo{}
class Ex_Database_Driver_Mongo extends Driver_Database_Driver_Mongo{}