<?php
exit;


class Form extends Library_MyQEE_Administration_Form{}
class EX_Form extends Library_MyQEE_Administration_Form{}

class Session extends Library_MyQEE_Administration_Session{}
class EX_Session extends Library_MyQEE_Administration_Session{}

class ORM_Admin_Member_Finder extends Library_MyQEE_Administration_ORM_Admin_Member_Finder{}
class EX_ORM_Admin_Member_Finder extends Library_MyQEE_Administration_ORM_Admin_Member_Finder{}

class ORM_Admin_Member_Data extends Library_MyQEE_Administration_ORM_Admin_Member_Data{}
class EX_ORM_Admin_Member_Data extends Library_MyQEE_Administration_ORM_Admin_Member_Data{}

class ORM_Admin_Member_Result extends Library_MyQEE_Administration_ORM_Admin_Member_Result{}
class EX_ORM_Admin_Member_Result extends Library_MyQEE_Administration_ORM_Admin_Member_Result{}

class ORM_Admin_MemberGroup_Finder extends Library_MyQEE_Administration_ORM_Admin_MemberGroup_Finder{}
class EX_ORM_Admin_MemberGroup_Finder extends Library_MyQEE_Administration_ORM_Admin_MemberGroup_Finder{}

class ORM_Admin_MemberGroup_Data extends Library_MyQEE_Administration_ORM_Admin_MemberGroup_Data{}
class EX_ORM_Admin_MemberGroup_Data extends Library_MyQEE_Administration_ORM_Admin_MemberGroup_Data{}

class ORM_Admin_MemberGroup_Result extends Library_MyQEE_Administration_ORM_Admin_MemberGroup_Result{}
class EX_ORM_Admin_MemberGroup_Result extends Library_MyQEE_Administration_ORM_Admin_MemberGroup_Result{}

class Model_Admin_Administrator extends Library_MyQEE_Administration_Model_Admin_Administrator{}
class EX_Model_Admin_Administrator extends Library_MyQEE_Administration_Model_Admin_Administrator{}

class Model_Admin extends Library_MyQEE_Administration_Model_Admin{}
class EX_Model_Admin extends Library_MyQEE_Administration_Model_Admin{}