<?php
exit;


class Form extends Library_MyQEE_Administration_Form{}
class EX_Form extends Library_MyQEE_Administration_Form{}

class Session extends Library_MyQEE_Administration_Session{}
class EX_Session extends Library_MyQEE_Administration_Session{}

class ORM_Admin_Member_Finder extends Library_MyQEE_Administration_ORM_Admin_Member_Finder{}
class EX_ORM_Admin_Member_Finder extends Library_MyQEE_Administration_ORM_Admin_Member_Finder{}

class ORM_Admin_Member_Data extends Library_MyQEE_Administration_ORM_Admin_Member_Data{}
class EX_ORM_Admin_Member_Data extends Library_MyQEE_Administration_ORM_Admin_Member_Data{}

class ORM_Admin_Member_Result extends Library_MyQEE_Administration_ORM_Admin_Member_Result{}
class EX_ORM_Admin_Member_Result extends Library_MyQEE_Administration_ORM_Admin_Member_Result{}

class ORM_Admin_MemberGroup_Finder extends Library_MyQEE_Administration_ORM_Admin_MemberGroup_Finder{}
class EX_ORM_Admin_MemberGroup_Finder extends Library_MyQEE_Administration_ORM_Admin_MemberGroup_Finder{}

class ORM_Admin_MemberGroup_Data extends Library_MyQEE_Administration_ORM_Admin_MemberGroup_Data{}
class EX_ORM_Admin_MemberGroup_Data extends Library_MyQEE_Administration_ORM_Admin_MemberGroup_Data{}

class ORM_Admin_MemberGroup_Result extends Library_MyQEE_Administration_ORM_Admin_MemberGroup_Result{}
class EX_ORM_Admin_MemberGroup_Result extends Library_MyQEE_Administration_ORM_Admin_MemberGroup_Result{}

abstract class Controller_Admin_P extends Library_MyQEE_Administration_Controller_Admin_P{}
abstract class EX_Controller_Admin_P extends Library_MyQEE_Administration_Controller_Admin_P{}

abstract class Controller_Admin extends Library_MyQEE_Administration_Controller_Admin{}
abstract class EX_Controller_Admin extends Library_MyQEE_Administration_Controller_Admin{}

abstract class Controller_Administrator_Group extends Library_MyQEE_Administration_Controller_Administrator_Group{}
abstract class EX_Controller_Administrator_Group extends Library_MyQEE_Administration_Controller_Administrator_Group{}

abstract class Controller_Administrator_Index extends Library_MyQEE_Administration_Controller_Administrator_Index{}
abstract class EX_Controller_Administrator_Index extends Library_MyQEE_Administration_Controller_Administrator_Index{}

abstract class Controller_Index extends Library_MyQEE_Administration_Controller_Index{}
abstract class EX_Controller_Index extends Library_MyQEE_Administration_Controller_Index{}

abstract class Controller_Install extends Library_MyQEE_Administration_Controller_Install{}
abstract class EX_Controller_Install extends Library_MyQEE_Administration_Controller_Install{}

abstract class Controller_Login extends Library_MyQEE_Administration_Controller_Login{}
abstract class EX_Controller_Login extends Library_MyQEE_Administration_Controller_Login{}

abstract class Controller_Statics extends Library_MyQEE_Administration_Controller_Statics{}
abstract class EX_Controller_Statics extends Library_MyQEE_Administration_Controller_Statics{}

class Model_Admin_Administrator extends Library_MyQEE_Administration_Model_Admin_Administrator{}
class EX_Model_Admin_Administrator extends Library_MyQEE_Administration_Model_Admin_Administrator{}

class Model_Admin extends Library_MyQEE_Administration_Model_Admin{}
class EX_Model_Admin extends Library_MyQEE_Administration_Model_Admin{}