<?php
exit;


class Database_Driver_PDO_Result extends Driver_Database_Driver_PDO_Result{}
class Ex_Database_Driver_PDO_Result extends Driver_Database_Driver_PDO_Result{}

class Database_Driver_PDO_Transaction extends Driver_Database_Driver_PDO_Transaction{}
class Ex_Database_Driver_PDO_Transaction extends Driver_Database_Driver_PDO_Transaction{}

class Database_Driver_PDO extends Driver_Database_Driver_PDO{}
class Ex_Database_Driver_PDO extends Driver_Database_Driver_PDO{}