<?php
exit;


class Database_Drive_MySQL_Result extends Drive_Database_Drive_MySQL_Result{}
class Ex_Database_Drive_MySQL_Result extends Drive_Database_Drive_MySQL_Result{}

class Database_Drive_MySQL_Transaction extends Drive_Database_Drive_MySQL_Transaction{}
class Ex_Database_Drive_MySQL_Transaction extends Drive_Database_Drive_MySQL_Transaction{}

class Database_Drive_MySQL extends Drive_Database_Drive_MySQL{}
class Ex_Database_Drive_MySQL extends Drive_Database_Drive_MySQL{}