<?php
exit;


class Database_Driver_MySQLI_Result extends Driver_Database_Driver_MySQLI_Result{}
class Ex_Database_Driver_MySQLI_Result extends Driver_Database_Driver_MySQLI_Result{}

class Database_Driver_MySQLI_Transaction extends Driver_Database_Driver_MySQLI_Transaction{}
class Ex_Database_Driver_MySQLI_Transaction extends Driver_Database_Driver_MySQLI_Transaction{}

class Database_Driver_MySQLI extends Driver_Database_Driver_MySQLI{}
class Ex_Database_Driver_MySQLI extends Driver_Database_Driver_MySQLI{}