<?php
exit;


class Database_Driver_SQLite_Result extends Driver_Database_Driver_SQLite_Result{}
class Ex_Database_Driver_SQLite_Result extends Driver_Database_Driver_SQLite_Result{}

class Database_Driver_SQLite extends Driver_Database_Driver_SQLite{}
class Ex_Database_Driver_SQLite extends Driver_Database_Driver_SQLite{}